---
title: "Client Report - The War with Star Wars"
subtitle: "Course DS 250"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *
# add the additional libraries you need to import for ML here

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# df = pd.read_csv("https://github.com/fivethirtyeight/data/raw/master/star-wars-survey/StarWars.csv", encoding = "ISO-8859-1")

df_cols = pd.read_csv("https://github.com/fivethirtyeight/data/raw/master/star-wars-survey/StarWars.csv", encoding_errors = "ignore", nrows=1).melt()

df_cols = (
df_cols.replace("Response", "")
       .replace(np.nan, "")
       .replace("^Unnamed.*", "", regex = True)
       .replace(r"Star Wars: (Episode \w{1,3}) .*", r"\1", regex = True)
)

df_cols.iloc[3:9, 0] = "seen_"
df_cols.iloc[9:15, 0] = "rank_"
df_cols.iloc[15:29, 0] = "fav_"

df_cols['newnames'] = df_cols['variable'] + df_cols['value']
df_cols
```

```{python}
df = pd.read_csv("https://github.com/fivethirtyeight/data/raw/master/star-wars-survey/StarWars.csv", encoding_errors = "ignore", skiprows = 2, names = df_cols['newnames'])

df
```

## Elevator pitch
_A SHORT (2-3 SENTENCES) PARAGRAPH THAT `DESCRIBES KEY INSIGHTS` TAKEN FROM METRICS IN THE PROJECT RESULTS THINK TOP OR MOST IMPORTANT RESULTS._ (Note: this is not a summary of the project, but a summary of the results.)

_A Client has requested this analysis and this is your one shot of what you would say to your boss in a 2 min elevator ride before he takes your report and hands it to the client._

## QUESTION|TASK 1

__Shorten the column names and clean them up for easier use with pandas.__ Provide a table or list that exemplifies how you fixed the names. 

I hard coded some shorter titles using iloc[] and used regex to work with the movie title

```{python}

# Show cleaned names
cleaned = df.columns


print(cleaned)

```


## QUESTION|TASK 2

__Clean and format the data so that it can be used in a machine learning model.__ As you format the data, you should complete each item listed below. In your final report provide example(s) of the reformatted data with a short description of the changes made.  
    a. Filter the dataset to respondents that have seen at least one film  
    a. Create a new column that converts the age ranges to a single number. Drop the age range categorical column  
    a. Create a new column that converts the education groupings to a single number. Drop the school categorical column  
    a. Create a new column that converts the income ranges to a single number. Drop the income range categorical column  
    a. Create your target (also known as “y” or “label”) column based on the new income range column  
    a. One-hot encode all remaining categorical columns   

Filter the dataset to respondents that have seen at least one film  

```{python}
# Include and execute your code here
df_atleast1 = df.dropna(subset = ['seen_Episode I', 'seen_Episode II', 'seen_Episode III', 'seen_Episode IV', 'seen_Episode V', 'seen_Episode VI'], how = 'all')
```

```{python}
#| eval: False
#| include: False
#| echo: False

#alternative approaches
df['num_seen'] = df.loc[ : , 'seen_Episode I':'seen_Episode VI'].notna().sum(axis = 1)

df['num_seen'] = df.loc[ : , 'seen_Episode I':'seen_Episode VI'].isna().all(axis = 1)

df_atleast1 = df.query('num_seen > 0')
df_atleast = df[df['num_seen']]
```

Convert age to a numeric variable

```{python}
age_replace = {'45-60': 52, '> 60': 65, '30-44': 37, '18-29': 23.5}

# shouldn't have to drop 'Age' here right?
df_atleast1 = df_atleast1.replace(age_replace)
```

Convert income to a numeric variable

```{python}
# Include and execute your code here
df_atleast1['income'] = df_atleast1['Household Income'].str.extract(r"\$(\d*)").astype(float) #or you can use "Int64", but int gives an error


df_atleast1['income2'] = df_atleast1['Household Income'].str.replace(r"\$(\d*),*\d* - \$(\d*).*", r'\1\2', regex = True)

# I drop "Household Income" later

```

Convert Education to numeric variable

```{python}
# Include and execute your code here
education = {'Bachelor degree': 16,
             'Some college or Associate degree': 14,
             'Graduate degree': 18,
             'High school degree': 12,
             'Less than high school degree': 10}

df_atleast1['education_numeric'] = df_atleast1['Education'].map(education)

#I drop "Education" later
```

Trying to convert the "seen" columns to 0's and 1's
```{python}
# Include and execute your code here
df_atleast1.loc[:, 'seen_Episode I':'seen_Episode VI'] = df_atleast1.loc[:, 'seen_Episode I':'seen_Episode VI'].notna()

df_atleast1.loc[:, 'seen_Episode I':'seen_Episode VI'] = df_atleast1.loc[:, 'seen_Episode I':'seen_Episode VI'].astype('float')
```

```{python}
# Include and execute your code here
df_atleast1 = df_atleast1.replace({r"Episode I":1, r"Episode V":1}, regex = True)

df_atleast1[df_atleast1.filter(regex = "seen_").columns]= df_atleast1.filter(regex = "^seen").fillna(0).astype(int)


```

```{python}
df_atleast1.filter(regex = "^seen").fillna(0, inplace = True)
```

```{python}
df_atleast1.loc[ : , 'seen_Episode I':'seen_Episode VI'] = df_atleast1.loc[ : , 'seen_Episode I':'seen_Episode VI'].applymap(lambda x: 1 if pd.notna(x) else 0)
```

Convert the favorability ratings to numeric

```{python}
fav_dict = {'Very favorably': 5,
            'Somewhat favorably': 4,
            'Neither favorably nor unfavorably (neutral)': 3,
            'Unfamiliar (N/A)': 3,
            'Somewhat unfavorably': 2,
            'Very unfavorably': 1}

df_fav = df_atleast1.replace(fav_dict)
```

One hot all the remaining categorical variables

```{python}
df_fav2 = df_fav.drop(['income2', 'Education', 'Household Income', 'Age', 'Do you consider yourself to be a fan of the Expanded Universe?'], axis = 1)

df_dummy = pd.get_dummies(df_fav2, columns = df_fav2.select_dtypes(include = "object").columns).astype(float)
```

Create our target variable

```{python}
df_income_present = df_dummy.dropna(subset = 'income')

df_income_present['over50'] = (df_income_present['income'] >=50).astype(float)
```

## QUESTION|TASK 3

__Validate that the data provided on GitHub lines up with the article by recreating 2 of the visuals from the article.__  

_type your results and analysis here_

```{python}
# Include and execute your code here

```

```{python}
# Include and execute your code here

```

## QUESTION|TASK 4

__Build a machine learning model that predicts whether a person makes more than $50k. Describe your model and report the accuracy.__ 

_type your results and analysis here_

```{python}
# Include and execute your code here

```

---

## STRETCH QUESTION|TASK 1

__Build a machine learning model that predicts whether a person makes more than $50k. With accuracy of at least 65%. Describe your model and report the accuracy.__

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 2

__Validate the data provided on GitHub lines up with the article by recreating a 3rd visual from the article.__

_type your results and analysis here_

```{python}
# Include and execute your code here


```


## STRETCH QUESTION|TASK 3

__Create a new column that converts the location groupings to a single number. Drop the location categorical column.__  

_type your results and analysis here_

```{python}
# Include and execute your code here


```

---
